// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package krs

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *PackMessage) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "type":
			{
				var zb0002 string
				zb0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = PackMessageType(zb0002)
			}
		case "text":
			z.Text, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Text")
				return
			}
		case "pcm":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "PCM")
				return
			}
			if cap(z.PCM) >= int(zb0003) {
				z.PCM = (z.PCM)[:zb0003]
			} else {
				z.PCM = make([]float32, zb0003)
			}
			for za0001 := range z.PCM {
				z.PCM[za0001], err = dc.ReadFloat32()
				if err != nil {
					err = msgp.WrapError(err, "PCM", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PackMessage) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.Text == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.PCM == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "type"
		err = en.Append(0xa4, 0x74, 0x79, 0x70, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(string(z.Type))
		if err != nil {
			err = msgp.WrapError(err, "Type")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "text"
			err = en.Append(0xa4, 0x74, 0x65, 0x78, 0x74)
			if err != nil {
				return
			}
			err = en.WriteString(z.Text)
			if err != nil {
				err = msgp.WrapError(err, "Text")
				return
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "pcm"
			err = en.Append(0xa3, 0x70, 0x63, 0x6d)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.PCM)))
			if err != nil {
				err = msgp.WrapError(err, "PCM")
				return
			}
			for za0001 := range z.PCM {
				err = en.WriteFloat32(z.PCM[za0001])
				if err != nil {
					err = msgp.WrapError(err, "PCM", za0001)
					return
				}
			}
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PackMessage) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.Text == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.PCM == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	o = append(o, 0x80|uint8(zb0001Len))

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// string "type"
		o = append(o, 0xa4, 0x74, 0x79, 0x70, 0x65)
		o = msgp.AppendString(o, string(z.Type))
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// string "text"
			o = append(o, 0xa4, 0x74, 0x65, 0x78, 0x74)
			o = msgp.AppendString(o, z.Text)
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// string "pcm"
			o = append(o, 0xa3, 0x70, 0x63, 0x6d)
			o = msgp.AppendArrayHeader(o, uint32(len(z.PCM)))
			for za0001 := range z.PCM {
				o = msgp.AppendFloat32(o, z.PCM[za0001])
			}
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PackMessage) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "type":
			{
				var zb0002 string
				zb0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Type")
					return
				}
				z.Type = PackMessageType(zb0002)
			}
		case "text":
			z.Text, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Text")
				return
			}
		case "pcm":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PCM")
				return
			}
			if cap(z.PCM) >= int(zb0003) {
				z.PCM = (z.PCM)[:zb0003]
			} else {
				z.PCM = make([]float32, zb0003)
			}
			for za0001 := range z.PCM {
				z.PCM[za0001], bts, err = msgp.ReadFloat32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "PCM", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PackMessage) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(string(z.Type)) + 5 + msgp.StringPrefixSize + len(z.Text) + 4 + msgp.ArrayHeaderSize + (len(z.PCM) * (msgp.Float32Size))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PackMessageType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = PackMessageType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z PackMessageType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteString(string(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z PackMessageType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendString(o, string(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PackMessageType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = PackMessageType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z PackMessageType) Msgsize() (s int) {
	s = msgp.StringPrefixSize + len(string(z))
	return
}
